import HubRemoval
open HubRemoval

/-! Every Lean name cited in `paper/hub_removal.tex` and in the README status tables exists.
This file is generated from those two documents; each `#check` fails if its name is missing. -/

#check @GoodT.mono
#check @N_sub_psi_eq
#check @PhiK_le_max
#check @PhiK_le_psi
#check @abs_card_edges_sub_le
#check @abs_card_hubEdges_sub_le
#check @attach_mutual
#check @buchstab
#check @buchstab_real
#check @card_common_multiples_ge
#check @card_edges_zero
#check @card_fibre_le
#check @card_fibre_le_K
#check @card_fibre_le_psi
#check @card_hubEdges
#check @card_multiples_Ioc_ge
#check @card_obst_ge
#check @card_smoothFibre
#check @cofactor_le_B
#check @cor_degree_adaptive
#check @cor_degree_static
#check @cor_profile
#check @cor_structure
#check @cor_structure_prob
#check @cor_structure_whp
#check @cor_upper_profile
#check @cor_upper_profile_eventually
#check @core_a
#check @core_b
#check @core_c
#check @core_d
#check @core_d'
#check @core_divisors
#check @degT_ge
#check @degT_le_deg
#check @deg_le
#check @dickLim
#check @dickLim_continuous
#check @dickLim_of_le_half
#check @dickLim_strictAntiOn
#check @dickman
#check @dickman_asymptotic
#check @dickman_eq_one_sub_log
#check @dickman_hasDerivAt
#check @dickman_integral
#check @dickman_le_one
#check @dickman_le_two_div
#check @dickman_pos
#check @dickman_strictAntiOn
#check @dickman_tendstoUniformlyOn
#check @dickman_tendsto_zero
#check @dickman_unique
#check @divisor_bound
#check @divisor_bound_explicit
#check @doubling
#check @doubling_connected
#check @dvd_three_primes
#check @edgeMul
#check @eq_4_2
#check @eq_4_2_core
#check @eventually_attach_cond
#check @eventually_goodN
#check @eventually_goodT
#check @eventually_mul_log_pow_le
#check @exists_divisor_of_subsum
#check @exists_dvd_mem_Ico
#check @expectP_comp_injective
#check @expectP_mul_of_disjoint
#check @expectP_prod_of_pairwiseDisjoint
#check @expect_maxSCC_Ioc
#check @expect_secondSCC_ge
#check @fibre_one
#check @fixedN_sandwich'
#check @gap_le_of_good
#check @goodSet_mem_smoothFibre
#check @hub_edge_share
#check @kp_corollary_2
#check @lemma_2_1
#check @log_div_log_mem
#check @lower_bound
#check @lower_bound_err'
#check @maxSCC_Ioc_antitone
#check @maxSCC_mono
#check @mertens_a
#check @mertens_a_real
#check @mertens_b
#check @mertens_b_nat
#check @mertens_c
#check @mertens_d
#check @mul_dickman_eq_integral
#check @obst_goodSet
#check @obst_mem
#check @primeSum_integral
#check @prob_PhiK_le_K
#check @prob_all_bit
#check @prob_and_ge
#check @prob_attach
#check @prob_attachEv
#check @prob_attachEv_eq
#check @prob_attachEv_ge
#check @prob_attach_ge
#check @prob_cylinder
#check @prob_exists_le
#check @prob_no_pat
#check @prob_not_hub
#check @prob_not_robust
#check @prob_not_robust_exp
#check @prob_or_of_disjoint
#check @prob_pat
#check @psi_dickman_base
#check @psi_dickman_nat
#check @psi_dickman_step
#check @psi_div_le
#check @psi_eq_PsiR_rpow
#check @psi_eq_self_of_le
#check @psi_limit
#check @psi_nonprime_step
#check @psi_prime_step
#check @psi_upper
#check @psi_upper'
#check @rate_cases
#check @reachable_two_pow_mul
#check @remark_2_5
#check @remark_3_4
#check @remark_3_4_holds
#check @remark_5_1
#check @remark_5_2
#check @remark_5_3_slow
#check @remark_5_3_uniform
#check @remark_5_3_uniform_main
#check @remark_7_2
#check @remark_7_2_hubs
#check @remark_7_2_small
#check @robust_adj
#check @robust_pair
#check @robust_reachable
#check @roughPart_eq_of_edge
#check @roughPart_eq_of_reachable
#check @sandwich_adaptive
#check @sandwich_static
#check @secondSCC_ge
#check @sigmaSet_closed
#check @sigmaSet_mutual
#check @sigmaSet_subset
#check @sigma_mutual
#check @sigma_subset_smoothFibre
#check @slow_rho_bound
#check @slow_rho_bound_explicit
#check @smallK_psi
#check @static_eq_Icc
#check @step_bound
#check @stronglyConnected_card_le_max
#check @stronglyConnected_card_le_psi
#check @stronglyConnected_subset_fibre
#check @subsum
#check @subsum_infinite
#check @subsum_of_mem_Icc
#check @subsum_sharp
#check @sum_log_div_le
#check @sum_log_smooth_le
#check @sum_primesBetween_inv
#check @sum_weight
#check @sum_wt
#check @theta_le
#check @thm_main
#check @thm_rate
#check @three_primes_goodSet
#check @three_primes_mem
#check @tk_AG
#check @tk_E
#check @tk_core
#check @turan_count
#check @turan_kubilius
#check @turan_variance
